//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTIVE
    {
        public string USN { get; set; }
        public string ELECTIVE1 { get; set; }
        public string ELECTIVE2 { get; set; }
        public string ELECTIVE3 { get; set; }
        public string ELECTIVE4 { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
